CREATE TABLE IF NOT EXISTS members;
CREATE TABLE IF NOT EXISTS pledges;
CREATE TABLE IF NOT EXISTS pledge_amounts;
CREATE TABLE IF NOT EXISTS requests;
CREATE TABLE IF NOT EXISTS users;
CREATE TABLE IF NOT EXISTS user_detail;
CREATE TABLE IF NOT EXISTS user_password_reset;
